# Generated by Django 4.1.7 on 2023-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=2)),
                ('atomic_number', models.IntegerField()),
                ('atomic_weight', models.DecimalField(decimal_places=8, default=0.0, max_digits=12)),
            ],
        ),
    ]
